TAP_DANCE_ENABLE = yes
LEADER_ENABLE = yes
RGB_MATRIX_ENABLE = yes
BOOTMAGIC_ENABLE=no
COMMAND_ENABLE=no
SLEEP_LED_ENABLE=no
FORCE_NKRO ?= yes
DEBUG_ENABLE = no
CONSOLE_ENABLE = no
MOUSEKEY_ENABLE = no

OPT_DEFS += -DUSER_PRINT

EXTRAFLAGS += -flto
